### PR TITLE
Updating Linting rules

### LINKED ISSUE #148: Integrate latest scss-lint Gem and adjust config accordingly

### PR DESCRIPTION
**Pull request by chris-pearce**
This closes #148.

@AlecRaeside @kllevin you'll need to update your AEM lint file. Also @AlecRaeside can you help Sean set up linting on SSO?

### CODE REVIEW

**Comment by onemarketnetworkllc** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://builds.westfieldlabs.com//job/PR-scally/83/
Test PASSed.

**Comment by smgcode** [comment]
LGTM - Probably need @kate or @AlecRaeside to look over also. 

@AlecRaeside - let me know what needs to be done to set it up for SSO. Thanks :)

**Comment by chris-pearce** [comment]
CC @gabrielrinaldi

**Comment by onemarketnetworkllc** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://builds.westfieldlabs.com//job/PR-scally/84/
Test PASSed.

**Comment by AlecRaeside** [comment]
centre-site inherits from scally config so it will automatically get the update

**Comment by AlecRaeside** [comment]
yep I'll work with @smgcode  on linting in sso

**Comment by AlecRaeside** [comment]
LGTM

**Comment by kllevin** [comment]
LGTM

**Pull request merged**
