### PR TITLE
Fixing depracation warning for Sass compile

### PR DESCRIPTION
**Pull request by chris-pearce**

### CODE REVIEW

**Comment by smgcode** [comment]
I also get the deprecation warning here: https://github.com/westfieldlabs/scally/blob/master/utilities/_u-drop-down.scss#L104 otherwise LGTM

**Comment by chris-pearce** [comment]
@smgcode I'm not getting that warning, weird?

**Comment by kllevin** [comment]
LGTM

**Comment by chris-pearce** [comment]
Closes: #49

**Pull request merged**
