### PR TITLE
Adding new utility: Overflow

### PR DESCRIPTION
**Pull request by chris-pearce**

### CODE REVIEW

**Comment by chris-pearce** [comment]
This closes #123.

**Comment by AlecRaeside** [comment]
LGTM

**Comment by kllevin** [comment]
LGTM

**Comment by smgcode** [comment]
For the codepen: http://codepen.io/team/westfieldlabs/full/xFHfk are the examples supposed to have set dimensions or does that promote bad practice? I was looking at: http://css-tricks.com/examples/OverflowExample/

**Comment by chris-pearce** [comment]
@smgcode no.

**Pull request merged**
