### PR TITLE
fix occurences of single quotes needing to be backticks

### PR DESCRIPTION
**Pull request by kllevin**

### CODE REVIEW

**Comment by onemarketnetworkllc** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://builds.westfieldlabs.com//job/PR-scally/88/
Test PASSed.

**Comment by onemarketnetworkllc** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://builds.westfieldlabs.com//job/PR-scally/89/
Test PASSed.

**Comment by AlecRaeside** [comment]
LGTM

**Comment by chris-pearce** [comment]
LGTM

**Pull request merged**
