### PR TITLE
Adding button faux link component

### LINKED ISSUE #78: New component: Faux link
A component that makes a button look like a link

### PR DESCRIPTION
**Pull request by chris-pearce**
This closes #78.

### CODE REVIEW

**Comment by onemarketnetworkllc** [comment]
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
http://builds.westfieldlabs.com//job/PR-scally/85/
Test PASSed.

**Comment by chris-pearce** [comment]
CC @gabrielrinaldi

**Comment by AlecRaeside** [comment]
LGTM

**Comment by smgcode** [comment]
LGTM

**Comment by kllevin** [comment]
LGTM

**Pull request merged**
