### PR TITLE
Rakefile cleanups

### PR DESCRIPTION
**Pull request by chris-pearce**

### CODE REVIEW

**Comment by AlecRaeside** [comment]
LGTM but should get some other eyes on it

**Comment by smgcode** [comment]
@gabrielrinaldi @kllevin? ^

**Comment by kllevin** [comment]
I am assuming when you run this locally all is good?

**Comment by kllevin** [comment]
LGTM

**Comment by chris-pearce** [comment]
> > I am assuming when you run this locally all is good?

Yes

**Pull request merged**
