### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by chris-pearce**

### CODE REVIEW

**Comment by smgcode** [comment]
Would it be worth linking our styleguide for CSS/HTML/JS since that's the format Scally follows? https://github.com/westfield/css_guidelines. I know it's not open source yet, but if it does become so. Just a thought.

**Comment by AlecRaeside** [comment]
LGTM

**Comment by chris-pearce** [comment]
@smgcode good suggestion: https://github.com/westfieldlabs/scally/issues/68.

@AlecRaeside thanks for merging my PR ;)

**Comment by smgcode** [comment]
LGTM

**Pull request merged**
